export const INITIALIZE = "INITIALIZE";
export const INITIALIZE_SUCCESS = "INITIALIZE_SUCCESS";
export const INITIALIZE_ERROR = "INITIALIZE_ERROR";

export const REQUEST_FIREBASE = "REQUEST_FIREBASE";
export const RECIEVED_FIREBASE = "RECIEVED_FIREBASE";
export const RECIEVED_FIREBASE_ERROR = "RECIEVED_FIREBASE_ERROR";
export const CLEAR_FIREBASE = "CLEAR_FIREBASE";

export const ADD_EXERCISE = "ADD_EXERCISE";
export const ADD_EXERCISE_SUCCESS = "ADD_EXERCISE_SUCCESS";
export const ADD_EXERCISE_ERROR = "ADD_EXERCISE_ERROR";
