export const INITIALIZE = "INITIALIZE";
export const INITIALIZE_SUCCESS = "INITIALIZE_SUCCESS";
export const INITIALIZE_ERROR = "INITIALIZE_ERROR";

export const REQUEST_FIREBASE = "REQUEST_FIREBASE";
export const RECIEVED_FIREBASE = "RECIEVED_FIREBASE";
export const RECIEVED_FIREBASE_ERROR = "RECIEVED_FIREBASE_ERROR";
export const CLEAR_FIREBASE = "CLEAR_FIREBASE";
